"""FastAPI request/response models."""

from typing import List, Optional

from pydantic import BaseModel, Field

from agent.product.schemas import ProductGenSchema


class ProductGenerateRequest(BaseModel):
    """Request model for product generation."""

    name: str = Field(..., description="Product name (in Russian)", min_length=1)
    brand: str = Field(..., description="Product brand", min_length=1)
    price: int = Field(..., ge=0, description="Product price")
    stock: Optional[int] = Field(default=5, ge=0, description="Product stock quantity")
    # Note: Images are automatically generated by AI agent, not requested from user


class ProductGenerateResponse(BaseModel):
    """Response model for product generation."""

    name: str = Field(..., description="Product name in Russian")
    description: str = Field(..., description="Product description in Russian")
    meta_title: str = Field(..., description="Meta title in Russian")
    meta_description: str = Field(..., description="Meta description in Russian")
    tags: List[str]
    price: int
    stock: int
    shop_saved: Optional[bool] = Field(
        default=None, description="Do'konga saqlanganmi?"
    )
    shop_response: Optional[dict] = Field(default=None, description="Do'kon API javobi")

    @classmethod
    def from_schema(
        cls,
        schema: ProductGenSchema,
        shop_saved: Optional[bool] = None,
        shop_response: Optional[dict] = None,
    ) -> "ProductGenerateResponse":
        """Create response from ProductGenSchema."""
        return cls(
            name=schema.name,
            description=schema.description,
            meta_title=schema.meta_title,
            meta_description=schema.meta_description,
            tags=schema.tags,
            price=schema.price,
            stock=schema.stock,
            shop_saved=shop_saved,
            shop_response=shop_response,
        )


class ErrorResponse(BaseModel):
    """Error response model."""

    error: str = Field(..., description="Error message")
    detail: Optional[str] = Field(None, description="Error details")
